use serde::{ Deserialize, Serialize };
use derive_more::Constructor;

#[derive(Clone, Constructor, Debug, Deserialize, Serialize)]
pub struct Hits(u64);

impl Hits {
    // pub fn new(data: u64) -> Self {
    //     Self(data)
    // } this function is generated by the Constructor crate
    pub fn into_inner(self) -> u64 {
        self.0
    }
}